"""Add adages_lifecycle

Revision ID: d022812f427f
Revises: 7451beada0f0
Create Date: 2022-09-02 15:09:00.436170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd022812f427f'
down_revision = '7451beada0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adages_lifecycle', sa.Integer(), nullable=True))
    op.add_column('user_history', sa.Column('adages_lifecycle', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'adages_lifecycle')
    op.drop_column('user', 'adages_lifecycle')
    # ### end Alembic commands ###
