"""test int default value

Revision ID: eb950fb9cb2c
Revises: 7451beada0f0
Create Date: 2022-09-03 01:20:33.244214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb950fb9cb2c'
down_revision = '7451beada0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adages_lifecycle', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('user_history', sa.Column('adages_lifecycle', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'adages_lifecycle')
    op.drop_column('user', 'adages_lifecycle')
    # ### end Alembic commands ###
